### ISSUE TITLE
option to use point instead of comma as decimal separator for time lapses

### ISSUE THREAD

**Issue by Oxeda** [tattali/QLAddict#11]
Is there any way to change this behaviour? 

thank you very much

![Captura de Pantalla 2020-04-08 a la(s) 00 17 23](https://user-images.githubusercontent.com/7676526/78747162-56cdb600-792e-11ea-8647-f72a24b3ec87.jpg)

**Comment by tattali** [comment]
this is the default `.str` notation. Why do you need point intead of commas ?
