### ISSUE TITLE
Doesn't work on Big Sur 11.0.1

### ISSUE THREAD

**Issue by setanarut** [tattali/QLAddict#17]
Doesn't work on Big Sur 11.0.1

**Comment by tattali** [comment]
Sorry I don't have the bandwidth now but I will try before the end of the year

**Comment by tattali** [comment]
I cannot notarize the quicklook or find out how to notarize it in a simple and efficient way.
If you have any skills or know someone has, feel free to participate.
Thank you in advance for your help.

**Comment by nevertoday** [comment]
not working on mac mini m2?
