### ISSUE TITLE
Conflict with Subler

### ISSUE THREAD

**Issue by setanarut** [tattali/QLAddict#8]
The plugin does not work when [Subler](https://subler.org/) is installed. related to .srt identifier of Subler https://bitbucket.org/galad87/subler/src/master/Info.plist

**Comment by tattali** [comment]
Hi, is this working now?

**Comment by setanarut** [comment]
no, i prefer subler. When nobody was interested, I closed it.

**Comment by setanarut** [comment]
You should make my pull request the default theme, the default theme has a very ugly style.
